In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#load data
df=pd.read_csv("https://raw.githubusercontent.com/ArchanaInsights/Datasets/main/marketing_campaign.csv")
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22029 entries, 0 to 22028
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       22029 non-null  int64
 1   Company           22029 non-null  object
 2   Campaign_Type     22029 non-null  object
 3   Target_Audience   22029 non-null  object
 4   Duration          22029 non-null  object
 5   Channel_Used      22029 non-null  object
 6   Conversion_Rate   22029 non-null  float64
 7   Acquisition_Cost  22029 non-null  int64
 8   ROI               22029 non-null  float64
 9   Location          22029 non-null  object
 10  Language          22029 non-null  object
 11  Clicks            22029 non-null  int64
 12  Impressions       22029 non-null  int64
 13  Engagement_Score  22029 non-null  int64
 14  Customer_Segment  22029 non-null  object
 15  Date              22029 non-null  object
dtypes: float64(2), int64(5), object(9)
memory usage: 2.7+ MB

,Campaign_ID,Conversion_Rate,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score
count,22029.000000,22029.000000,22029.000000,22029.000000,22029.000000,22029.000000,22029.000000
mean,11015.000000,4.757232,5522.740842,182.863648,2223.807572,50610.402787,6.582323
std,6359.368876,0.960393,2597.666260,301.619721,1394.166380,28542.979123,1.458804
min,1.000000,2.015723,1000.000000,-98.300000,30.000000,1001.000000,4.000000
25%,5508.000000,4.130705,3286.000000,-4.080000,1067.000000,25804.000000,5.000000
50%,11015.000000,4.761527,5525.000000,93.650000,2088.000000,50858.000000,7.000000
75%,16522.000000,5.429335,7766.000000,247.310000,3212.000000,75165.000000,8.000000
max,22029.000000,7.469907,9999.000000,3109.790000,6887.000000,99999.000000,9.000000

In [ ]:
df.isnull()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22025,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22026,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22027,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22028,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22024,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22025,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22026,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22027,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
22028,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.isnull().sum()

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            0
Language            0
Clicks              0
Impressions         0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

AttributeError: module 'pandas' has no attribute 'to'